### ISSUE TITLE
ViewerController.focus tests failing on Firefox

### ISSUE THREAD

**Issue by mlewand** [cksource/ckeditor-plugin-a11ychecker#181]
The reason for it is that with change in 4.5.x related to `.cke_reset` selectors specifity (most likely [#13119](http://dev.ckeditor.com/ticket/13119)) is causing balloonpanel styles not to be applied.

As a result AC's balloonpanel close button is invisible, so focus manager is skipping this GUI element when looking for next/previous focus element.

Current `test focus trap` expect "previous" button to be focused, while it should focus close button (because this is the first focusable element).

**Comment by Tade0** [comment]
I guess this one is already fixed.
Results form Firefox: `282 passed / 0 failed in 17s 043ms - 100%`

**Comment by mlewand** [comment]
Correct I confirm that tests are passing on FF so it got fixed down the road, thanks!
