### ISSUE TITLE
Move button to the first position in toolbar so the arrow will always point the right icon

### ISSUE THREAD

**Issue by vokiel** [cksource/ckeditor-plugin-a11ychecker#186]
When building with CKEditor Basic preset the _Give it a try!_ is pointing on wrong button.

![sample_basic](https://cloud.githubusercontent.com/assets/422571/14114633/e8712378-f5d7-11e5-8c7a-0d095e1e40fa.png)

**Comment by mlewand** [comment]
Since this sample got removed, this issue is no longer valid.
