### ISSUE TITLE
Quick Fix for imgShouldNotHaveTitle

### ISSUE THREAD

**Issue by mlewand** [cksource/ckeditor-plugin-a11ychecker#201]
There is a problem when fixing a title for the image.

Current quick fix uses `AttributeRename` QF and blindly renames actual `title` to `alt` which is wrong because we might already have better/correct title in the place.

Actually this was a case in a particular use case:

1. Consider a sport car image that has no `alt` and `title` set to value "placeholder".
1. AC reports an issue that the image has no alt.
1. User sets the alt value to "sport car" and clicks the quick fix button.
1. AC reports an issue that the title attr should not be used, and suggests new alt value, setting it to "placeholder".

Result:

User is confused and might override the alt text that he has just set.

**Comment by mlewand** [comment]
There were no tests. I've added manual test, since I needed a place to check if it works.

The code works, so that's great, but we need unit tests for it and there are some code issues explained in PR code comments.

**Comment by Tade0** [comment]
Added unit tests, fixed style issues, refactored some parts as suggested in the PR comments.

On a side note: I checked the config and there is no rule for spaces before and after parentheses. I'm going to create an issue for that.

**Comment by mlewand** [comment]
Added my review comments into the PR.

**Comment by mlewand** [comment]
Fixed with git:d55e5914df (merged to master).
