### ISSUE TITLE
Remove viewer close handling from AC

### ISSUE THREAD

**Issue by Tade0** [cksource/ckeditor-plugin-a11ychecker#205]
Since this is already covered in the `balloonpanel` plugin we can remove the handler from AC.

**Comment by Tade0** [comment]
There's a slight difference that makes removing this handler questionable for now: The handler blurs the panel - which is important, but not done in the balloonpanel plugin yet.

**Comment by mlewand** [comment]
@f1ames I'll ask you to review this one.

**Comment by f1ames** [comment]
The code you moved to `balloonpanel` should be removed, but it was only commented out (https://github.com/cksource/ckeditor-plugin-a11ychecker/commit/1ef979a3909c98c38560082074ca6dc5b82bf6cd#commitcomment-17752628).

**Comment by Tade0** [comment]
Ouch. Updated.

**Comment by f1ames** [comment]
Thanks, now it's OK. This issue will be closed along with #208.

**Comment by f1ames** [comment]
While both this issue and related PR (#208) are R+, it could be merged to `master`. However, this changes are compatible with next CKEditor 4 major release (`4.6.0`). I am not sure if it should be already merged to `master` or if we should wait for CKEditor 4 major release (see also #223)?

WDYT @Tade0 @mlewand?
