### ISSUE TITLE
Deferment exception in manual test

### ISSUE THREAD

**Issue by mlewand** [cksource/ckeditor-plugin-a11ychecker#212]
There's an exception in manual test http://tests.ckeditor.dev:1030/plugins/a11ychecker/tests/manual/a11ychecker just few secs after loading is done.

> Uncaught Error: Deferment unlock timeout - "0" never unlocked

I believe it's due not calling pure `require` instead of `bender.require`.

**Comment by mlewand** [comment]
Review notes in a related PR.

**Comment by Tade0** [comment]
The PR in `benderjs-amd` referencing this issue was merged into `master` so now the error does not occur.

**Comment by mlewand** [comment]
Still we need to upgrade dependencies, because it was set to require benderjs-amd at version 0.2.3. I've fixed this in PR #217
