### ISSUE TITLE
Brazilian Portuguese Localization

### ISSUE THREAD

**Issue by gsag** [cksource/ckeditor-plugin-a11ychecker#224]
Hello, I wonder if you have plans to add a translation to Brazilian Portuguese? How could I help in the contribution of this translation? Thank you.

**Comment by mlewand** [comment]
Hi, currently we don't have anyone who could work on Brazilian Portuguese, but we'd be happy with your contribution if this is what you're looking for!

At the moment we have very simple lang mechanism. The best way to contribute language would be by using GitHub Pull Request. To bring a new language, you'd need to create pt-br.js files in:

* [/lang](https://github.com/cksource/ckeditor-plugin-a11ychecker/tree/master/lang) directory.
* [/quickfix/lang](https://github.com/cksource/ckeditor-plugin-a11ychecker/tree/master/quickfix/lang) directory.
* Create `pt-br` property in each [Quail assessment title and description](https://github.com/cksource/ckeditor-plugin-a11ychecker/blob/master/libs/quail/tests.json).
* Include `pt-br` lang in [plugin.js](https://github.com/cksource/ckeditor-plugin-a11ychecker/blob/bead7de3c5cd3587102454cf383146fdcd5d420f/plugin.js#L18-L20) `lang` and `quickFixesLang` properties.

**Comment by gsag** [comment]
Hi, it would be nice to make this contribution to the project with my native language! I will check these requirements you told me and soon I hope to make a pull request. Thanks @mlewand ! :)

**Comment by mlewand** [comment]
That's great @gsag! We're looking forward for it, however we know that this is a little bit of work, so take your time.

I'll close this issue for now, once you have the translation please create a pull request, that will create a new issue for it. Thanks!
