### ISSUE TITLE
Balloon classes are localized, causing issues of a different testability look the same

### ISSUE THREAD

**Issue by ZacharyRead** [cksource/ckeditor-plugin-a11ychecker#233]
## Repro steps

Use Accessibility Checker in a language other than English.
Inspect content containing any accessibility issue.

### Expected

AC balloon has proper color cues.

![AC properly showing warning, with colors](https://i.imgur.com/WuaEV1u.png)

### Actual

All error levels look the same.

![AC showing warning, but no color cue](https://i.imgur.com/aUsFPK4.png)

## More details

If you translate the "testability" strings under /lang/LANGCODE.js (such as "error"), the plugin will use these strings to generate its classes. For example, "cke_a11yc_testability_error" becomes "cke_a11yc_testability_erreur" in French. Since "cke_a11yc_testability_erreur" isn't in the CSS file, it breaks the CSS rendering of the a11ychecker box.

I can't imagine what kind of class name it would generate if you were using a non-alphabet script, like Japanese or Chinese.

The class names should be consistent across all languages. If someone needs to override the default styling per language, they can just target it based on the CKEditor's language attribute,

**Comment by mlewand** [comment]
Thanks for the report, this is important issue.

**Comment by mlewand** [comment]
Added clear repro steps to the original description.
