### ISSUE TITLE
Find an alternative to QuailJS

### ISSUE THREAD

**Issue by mgifford** [cksource/ckeditor-plugin-a11ychecker#253]
For security reasons QuailJS should be replaced with an actively maintained library like [axe-core](https://www.axe-core.org/) or [pa11y](http://pa11y.org/).  

This is an outstanding issue in the Drupal community:
  https://www.drupal.org/project/ckeditor_a11ychecker/issues/2958494

If a JavaScript security person can explain why this isn't a concern, great. I just know in principle that unmaintained code should never be sitting on a production environment.

**Comment by mlewand** [comment]
Thanks @mgifford, this issue is already tracked in #242. Make sure to add 👍 reaction to support the issue.

**Comment by fuzzbomb** [comment]
pa11y is really just a wrapper around HTML CodeSniffer.
